In [1]:
!pip install selenium

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: selenium in /Users/admin/Library/Python/3.9/lib/python/site-packages (4.36.0)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Requirement already satisfied: trio<1.0,>=0.30.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from selenium) (0.31.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.6.15 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from selenium) (2025.10.5)
Requirement already satisfied: typing_extensions<5.0,>=4.14.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from selenium) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio<1.0,>=0.30.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio<1.0,>=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio<1.0,>=0.30.0->selenium) (3.11)
Requirement already satisfied: outcome in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio<1.0,>=0.30.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio<1.0,>=0.30.0->selenium) (1.3.1)
Requirement already satisfied: exceptiongroup in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio<1.0,>=0.30.0->selenium) (1.3.0)
Requirement already satisfied: wsproto>=0.14 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [2]:
!pip install webdriver_manager

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: webdriver_manager in /Users/admin/Library/Python/3.9/lib/python/site-packages (4.0.2)
Requirement already satisfied: requests in /Users/admin/Library/Python/3.9/lib/python/site-packages (from webdriver_manager) (2.32.5)
Requirement already satisfied: python-dotenv in /Users/admin/Library/Python/3.9/lib/python/site-packages (from webdriver_manager) (1.2.1)
Requirement already satisfied: packaging in /Users/admin/Library/Python/3.9/lib/python/site-packages (from webdriver_manager) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from requests->webdriver_manager) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from requests->webdriver_manager) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from requests->webdriver_manager) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from requests->webdriver_manager) (2025.10.5)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [3]:
from selenium import webdriver # 크롤링을 하기 위한 크롤러를 생성하도록 도와주는 역할
from selenium.webdriver.chrome.service import Service # 브라우저 드라이브 버전 세팅 도와주는 역할
from selenium.webdriver.chrome.options import Options # 크롤러가 어떤 환경에서 작동하도록 할 것인지 세팅 도와주는 역할
from webdriver_manager.chrome import ChromeDriverManager # 로컬 컴퓨터 내 크롬 브라우저 드라이브 버전을 찾아서 설치 후 크롤러에게 적용할 값을 생성해주는 역할

# 1) 해당 크롤러가 정상적인 브라우저의 역할
# - 현재 로컬 컴퓨터에 설치되어있는 크롬 브라우저의 드라이브 버전과 동일하게 세팅
service = Service(ChromeDriverManager().install()) # 현재 로컬 컴퓨터 내 크롬 브라우저 드라이브 버전 인스톨 및 값 저장

# 2) 해당 브라우저가 어떤 환경에서 작동하도록 할 것인지 환경 설정
options = Options()
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36")
# options.add_argument("--headless")
# options.add_argument("--disable-gpu")

driver = webdriver.Chrome(service=service, options=options) # driver가 실제 크롤러가 됩니다.

URL = "https://display.wconcept.co.kr/rn/women"

driver.get(URL) # 크롤러가 크롤링할 수 있도록 하는 메서드
print("wconcept 방문조회 완료")

wconcept 방문조회 완료

In [8]:
from selenium import webdriver # 크롤링을 하기 위한 크롤러를 생성하도록 도와주는 역할
from selenium.webdriver.common.by import By # 크롤러가 어떤 방식으로 값을 찾아오게 할지 도와주는 역할
from selenium.webdriver.chrome.service import Service # 브라우저 드라이브 버전 세팅 도와주는 역할
from selenium.webdriver.chrome.options import Options # 크롤러가 어떤 환경에서 작동하도록 할 것인지 세팅 도와주는 역할
from webdriver_manager.chrome import ChromeDriverManager # 로컬 컴퓨터 내 크롬 브라우저 드라이브 버전을 찾아서 설치 후 크롤러에게 적용할 값을 생성해주는 역할

import time

# 1) 해당 크롤러가 정상적인 브라우저의 역할
# - 현재 로컬 컴퓨터에 설치되어있는 크롬 브라우저의 드라이브 버전과 동일하게 세팅
service = Service(ChromeDriverManager().install()) # 현재 로컬 컴퓨터 내 크롬 브라우저 드라이브 버전 인스톨 및 값 저장

# 2) 해당 브라우저가 어떤 환경에서 작동하도록 할 것인지 환경 설정
options = Options()
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36")
# options.add_argument("--headless")
# options.add_argument("--disable-gpu")

driver = webdriver.Chrome(service=service, options=options) # driver가 실제 크롤러가 됩니다.

URL = "https://display.wconcept.co.kr/rn/women"

driver.get(URL) # 크롤러가 크롤링할 수 있도록 하는 메서드
time.sleep(3)

# wconcept > 베스트 카테고리 이동
# 요소 = element
# 
# best_button = driver.find_element(By.CSS_SELECTOR, "span.mnbrtm-inner")
best_button = driver.find_element(By.XPATH, "//span[text()='베스트']")
best_button.click()
time.sleep(3)

driver.quit() # 크롤러가 타겟 사이트 방문 후 원하는 데이터 수집 완료한 다음 가상 브라우저를 종료
print("wconcept 방문조회 완료")

wconcept 방문조회 완료

In [5]:
dir(driver) # dir() => 객체 요소가 사용가능한 속성 및 메서드 조회

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_authenticator_id',
 '_bidi_session',
 '_browser',
 '_browsing_context',
 '_check_if_window_handle_is_current',
 '_devtools',
 '_emulation',
 '_fedcm',
 '_file_detector',
 '_get_cdp_details',
 '_input',
 '_is_remote',
 '_mobile',
 '_network',
 '_permissions',
 '_request',
 '_require_fedcm_support',
 '_script',
 '_session',
 '_shadowroot_cls',
 '_start_bidi',
 '_storage',
 '_switch_to',
 '_unwrap_value',
 '_web_element_cls',
 '_webextension',
 '_websocket_connection',
 '_wrap_value',
 'add_cookie',
 'add_credential',
 'add_virtual_authenticator',
 'back',
 'bidi_connection',
 'browser',
 'browsing_context',
 'capabilities',
 'caps',
 'close',
 'command_executor',
 'create_web_element',
 'current_url',
 'current_window_handle',
 'delete_all_cookies',
 'delete_cookie',
 'delete_downloadable_files',
 'delete_network_conditions',
 'dialog',
 'download_file',
 'emulation',
 'error_handler',
 'execute',
 'execute_async_script',
 'execute_cdp_cmd',
 'execute_script',
 'fedcm',
 'fedcm_dialog',
 'file_detector',
 'file_detector_context',
 'find_element',
 'find_elements',
 'fire_session_event',
 'forward',
 'fullscreen_window',
 'get',
 'get_cookie',
 'get_cookies',
 'get_credentials',
 'get_downloadable_files',
 'get_issue_message',
 'get_log',
 'get_network_conditions',
 'get_pinned_scripts',
 'get_screenshot_as_base64',
 'get_screenshot_as_file',
 'get_screenshot_as_png',
 'get_sinks',
 'get_window_position',
 'get_window_rect',
 'get_window_size',
 'implicitly_wait',
 'input',
 'launch_app',
 'locator_converter',
 'log_types',
 'maximize_window',
 'minimize_window',
 'mobile',
 'name',
 'network',
 'options',
 'orientation',
 'page_source',
 'permissions',
 'pin_script',
 'pinned_scripts',
 'print_page',
 'quit',
 'refresh',
 'remove_all_credentials',
 'remove_credential',
 'remove_virtual_authenticator',
 'request',
 'save_screenshot',
 'script',
 'service',
 'session_id',
 'set_network_conditions',
 'set_page_load_timeout',
 'set_permissions',
 'set_script_timeout',
 'set_sink_to_use',
 'set_user_verified',
 'set_window_position',
 'set_window_rect',
 'set_window_size',
 'start_client',
 'start_desktop_mirroring',
 'start_devtools',
 'start_session',
 'start_tab_mirroring',
 'stop_casting',
 'stop_client',
 'storage',
 'supports_fedcm',
 'switch_to',
 'timeouts',
 'title',
 'unpin',
 'virtual_authenticator_id',
 'webextension',
 'window_handles']

In [9]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/admin/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/admin/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [30]:
from selenium import webdriver # 크롤링을 하기 위한 크롤러를 생성하도록 도와주는 역할
from selenium.webdriver.common.by import By # 크롤러가 어떤 방식으로 값을 찾아오게 할지 도와주는 역할
from selenium.webdriver.chrome.service import Service # 브라우저 드라이브 버전 세팅 도와주는 역할
from selenium.webdriver.chrome.options import Options # 크롤러가 어떤 환경에서 작동하도록 할 것인지 세팅 도와주는 역할
from webdriver_manager.chrome import ChromeDriverManager # 로컬 컴퓨터 내 크롬 브라우저 드라이브 버전을 찾아서 설치 후 크롤러에게 적용할 값을 생성해주는 역할

import pandas as pd # as = alias 약어. 별칭 | 별명
import time
import re

# 1) 해당 크롤러가 정상적인 브라우저의 역할
# - 현재 로컬 컴퓨터에 설치되어있는 크롬 브라우저의 드라이브 버전과 동일하게 세팅
service = Service(ChromeDriverManager().install()) # 현재 로컬 컴퓨터 내 크롬 브라우저 드라이브 버전 인스톨 및 값 저장

# 2) 해당 브라우저가 어떤 환경에서 작동하도록 할 것인지 환경 설정
options = Options()
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--window-size=1920,1080")
options.add_argument("--start-maximized")
options.add_argument("--lang=ko_KR")
options.add_argument("--no-sandbox")
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36")
# options.add_argument("--headless")
# options.add_argument("--disable-gpu")

driver = webdriver.Chrome(service=service, options=options) # driver가 실제 크롤러가 됩니다.

URL = "https://display.wconcept.co.kr/rn/women"

driver.get(URL) # 크롤러가 크롤링할 수 있도록 하는 메서드
time.sleep(3)

# 유틸리티 함수
# 235,900 -> 235900 : 0-9 사이의 정수가 아닌 값들을 모두 없애라!
# def to_int(text) :
#     num = re.sub(r"[^0-9]", "", text)
#     if num :
#         return int(num)
#     else :
#         return 0
        
def to_int(text) :
    num = re.sub(r"[^0-9]", "", text)
    return int(num) if num else 0

# wconcept > 베스트 카테고리 이동
# 요소 = element
# best_button = driver.find_element(By.CSS_SELECTOR, "span.mnbrtm-inner")
best_button = driver.find_element(By.XPATH, "//span[text()='베스트']")
best_button.click()
time.sleep(3)

# 상품 카드 크롤링
# find_elements -> list 자료구조 -> len()
items = driver.find_elements(By.CSS_SELECTOR, "div.product-item.item.type-all")
print(f"1. 찾은 상품 수: {len(items)}개")

# 상품별 수집 데이터 저장용 리스트 생성
products = list() # []

# 반복문을 활용한 개별 상품 정보 수집
for idx, item in enumerate(items, 1) :
    # 1) 각 상품별 순위 조회
    try :
        ranking_no = int(item.find_element(By.CSS_SELECTOR, "span.rank").text)
    except :
        ranking_no = 0

    # 2) 각 브랜드명 조회
    try :
        brand_name = item.find_element(By.CSS_SELECTOR, "span.text.title").text.strip()
    except :
        brand_name = ""

    # 3) 각 상품명 조회
    try :
        product_name = item.find_element(By.CSS_SELECTOR, "span.text.detail").text.strip()
    except :
        product_name = ""
    # print(product_name)

    # 4) 각 판매가 (소비자가, 할인가, 할인률) 조회
    price_box = item.find_element(By.CSS_SELECTOR, "span.prdc-price")

    try :
        original_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.customer-price").text.strip())
    except :
        original_price = 0
        
    sale_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-price").text.strip())

    try :
        discount_rate = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-discount").text.strip())
    except :
        discount_rate = 0
        
    # 5) 평점, 리뷰수, 좋아요수
    stats = item.find_element(By.CSS_SELECTOR, "span.stats")

    try :
        rating = float(stats.find_element(By.CSS_SELECTOR, "em.score").text.strip())
    except :
        rating = 0.0
        
    try :
        review_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.review span.text.cnt").text.strip())
    except :
        review_count = 0
        
    try :
        like_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.like span.text.cnt").text.strip())
    except :
        like_count = 0

    # 6) 상품상세페이지 URL
    img_src = item.find_element(By.CSS_SELECTOR, "span.img img").get_attribute("src")
    match = re.search(r"/(\d{9})[_.]", img_src)

    if match :
        product_id = match.group(1)
        product_url = f"https://www.wconcept.co.kr/Product/{product_id}"
    else :
        product_id = None
        product_url = ""

    products.append({
        "ranking_no": ranking_no,
        "product_id": product_id,
        "brand_name": brand_name,
        "product_name": product_name,
        "original_price": original_price,
        "sale_price": sale_price,
        "discount_rate": discount_rate,
        "rating": rating,
        "review_count": review_count,
        "like_count": like_count,
        "img_src": img_src,
        "product_url": product_url
    })

    # print(ranking_no, brand_name, product_name, original_price, sale_price, discount_rate, rating, review_count, like_count, product_id, product_url)
    # [미확보] 상세페이지 URL : https://www.wconcept.co.kr/Product/308324709
    # [확보] 썸네일이미지 URL : https://product-image.wconcept.co.kr/productimg/image/img1/09/308324709_RO49453.jpg
product_df = pd.DataFrame(products)

# driver.quit() # 크롤러가 타겟 사이트 방문 후 원하는 데이터 수집 완료한 다음 가상 브라우저를 종료
print("2. wconcept 상품기본 정보수집 완료")

# 리뷰 포함 크롤링 데이터 저장용 리스트
all_reviews = list()

for product in products[:1] :
    product_url = product["product_url"]

    # 상품 상세페이지 진입단계
    driver.get(product_url)

    time.sleep(3)

    # 상품 리뷰버튼 확인 및 클릭
    review_button = driver.find_element(By.CSS_SELECTOR, "#reviewCnt1")
    review_button.click()

    time.sleep(3)

    print("3. wconcept 상품상세페이지 진입")
    rows = driver.find_elements(By.CSS_SELECTOR, "tr")

    review_items = []
    
    for row in rows :
        # print(row)
    #     review_text_element = row.find_element(By.CSS_SELECTOR, "p.pdt_review_text")
    #     review_items.append(review_text_element)
        review_text_elements = row.find_elements(By.CSS_SELECTOR, "p.pdt_review_text")

        if len(review_text_elements) > 0 :
            review_items.append(row)
            
    for review_no, review in enumerate(review_items, 1) :
        # 리뷰 작성자
        reviewer = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right em").text.strip()
        
        # 리뷰 작성일
        review_date = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right span").text.strip()

        # 구매 옵션정보
        purchase_text = review.find_element(By.CSS_SELECTOR, "div.pdt_review_option span").text.strip()
        match = re.search(r'\d+', purchase_text)
        purchase_option = int(match.group(0))

        # 리뷰 본문
        review_text = review.find_element(By.CSS_SELECTOR, "p.pdt_review_text").text.strip()

        # 리뷰 별점
        star = review.find_element(By.CSS_SELECTOR, "div.star-grade > strong")
        style = star.get_attribute("style")
        match = re.search(r"width:\s*([0-9]+)%", style)
        if match :
            star_percent = float(match.group(1))
            review_rating = star_percent / 20
        else :
            review_rating = 0.0
        # width:100%

        # 리뷰 상세 평가 저장을 위한 딕셔너리 정의
        evaluations = {}

        # 리뷰 상세 평가
        evaluation_items = review.find_elements(By.CSS_SELECTOR, "ul.product_review_evaluation > li")
        for evaluation in evaluation_items :
            evalutaion_type = evaluation.find_element(By.CSS_SELECTOR, "strong").text.strip()
            evalutaion_value = evaluation.find_element(By.CSS_SELECTOR, "em").text.strip()
            evaluations[evalutaion_type] = evalutaion_value

        # 리뷰 이미지 저장용 리스트
        review_images = list()
        
        # 리뷰 이미지
        images = review.find_elements(By.CSS_SELECTOR, "ul.pdt_review_photo img")

        for image in images :
            image_url = image.get_attribute("src")
            review_images.append(image_url)

        review_data = {
            "product_id": product["product_id"],
            "brand_name": product["brand_name"],
            "product_name": product["product_name"],
            "product_url": product["product_url"],
            "review_no": review_no,
            "reviewer": reviewer,
            "review_date": review_date,
            "purchase_option": purchase_option,
            "review_text": review_text,
            "review_rating": review_rating,
            "evaluations": evaluations,
            "review_images": review_images
        }
        all_reviews.append(review_data)
        
        # print(review_no, reviewer, review_date, purchase_option, review_text, review_rating, evaluations, review_images)
        print("4. wconcept 상품별 리뷰데이터 수집 완료")

1. 찾은 상품 수: 200개
2. wconcept 상품기본 정보수집 완료
3. wconcept 상품상세페이지 진입
4. wconcept 상품별 리뷰데이터 수집 완료
4. wconcept 상품별 리뷰데이터 수집 완료
4. wconcept 상품별 리뷰데이터 수집 완료
4. wconcept 상품별 리뷰데이터 수집 완료
4. wconcept 상품별 리뷰데이터 수집 완료
4. wconcept 상품별 리뷰데이터 수집 완료

In [31]:
product_df

,ranking_no,product_id,brand_name,product_name,original_price,sale_price,discount_rate,rating,review_count,like_count,img_src,product_url
0,1,308324709,아디다스,[IH3992] TOKYO W,139000,66720,52,4.9,14,915,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308324709
1,2,308577412,디자인스킨,"[9/9-9/10, ] 플레이 테이블 소파(미끄럼틀+계단) (+벨크로덮개&미끄럼방지...",285000,160650,43,4.8,150,683,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308577412
2,3,308193105,반원 아틀리에,[9/10 단하루!] [유미 PICK]A3567 와플 래글런 티셔츠_Black,49000,26754,45,4.8,48,2040,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308193105
3,4,306115156,아디다스,TOKYO W - JI0183,139000,88960,36,4.9,2050,9999,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/306115156
4,5,306035261,아비스파,[30%쿠폰] [단독]Davie 데이비 메리제인 스퀘어토 플랫슈즈(2way)_F35...,99000,54740,44,4.9,2254,9999,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/306035261
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,308591206,로트르드민,[20%쿠폰] Silhouette White shirts,158000,110200,30,5.0,15,1477,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308591206
196,197,308943690,드로우핏 우먼,[30%쿠폰] [W컨셉 단독][드로우핏우먼 X 주미니] 코튼 포켓 워크 팬츠 [BE...,77000,51205,33,3.0,1,290,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308943690
197,198,308312312,뮤니에,FLOW BAG_7COLORS,149000,123148,17,4.9,167,7517,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308312312
198,199,308903655,시티브리즈,[라벤더 단독] 워셔블 브이넥 니트_5COLORS,79900,53133,33,5.0,9,290,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308903655
199,200,308918425,우이,[오늘이 마지막!] 에센셜 브이넥 가디건 크림 아이보리 OU2061,59000,39235,33,0.0,0,248,https://product-image.wconcept.co.kr/productim...,https://www.wconcept.co.kr/Product/308918425

In [32]:
product_reviews = pd.DataFrame(all_reviews)
product_reviews

,product_id,brand_name,product_name,product_url,review_no,reviewer,review_date,purchase_option,review_text,review_rating,evaluations,review_images
0,308324709,아디다스,[IH3992] TOKYO W,https://www.wconcept.co.kr/Product/308324709,1,tw******,2026.09.09,245,디자인과 색상은 사진과 동일합니다. 사이즈는 정사이즈 안 것 같아요.,5.0,"{'사이즈': '적당함', '색상': '같음', '발볼': '좁음'}",[https://media.wconcept.co.kr/review/308324709...
1,308324709,아디다스,[IH3992] TOKYO W,https://www.wconcept.co.kr/Product/308324709,2,he******,2026.09.08,240,나이키 245신어요. 정사이즈로 245 주문했다가 앞코가 너무 남아서 240으로 교...,5.0,"{'사이즈': '큼', '색상': '같음', '발볼': '적당함'}",[https://media.wconcept.co.kr/review/308324709...
2,308324709,아디다스,[IH3992] TOKYO W,https://www.wconcept.co.kr/Product/308324709,3,aa******,2026.09.02,230,예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐요 예뻐...,5.0,"{'사이즈': '적당함', '색상': '같음', '발볼': '적당함'}",[https://media.wconcept.co.kr/review/308324709...
3,308324709,아디다스,[IH3992] TOKYO W,https://www.wconcept.co.kr/Product/308324709,4,em******,2026.09.02,235,평소 아디다스 35신어서 35시켰어요 발볼넓은편입니다. 평소 240신는 칼발인 엄마...,5.0,"{'사이즈': '적당함', '색상': '비슷함', '발볼': '좁음'}",[https://media.wconcept.co.kr/review/308324709...
4,308324709,아디다스,[IH3992] TOKYO W,https://www.wconcept.co.kr/Product/308324709,5,cr******,2026.08.19,230,화면보다 실물 색상 훨씬 예쁘네요. 브라운과 스카이블루 색상의 조화가 경쾌하면서 포...,5.0,"{'사이즈': '큼', '색상': '같음', '발볼': '적당함'}",[https://media.wconcept.co.kr/review/308324709...
5,308324709,아디다스,[IH3992] TOKYO W,https://www.wconcept.co.kr/Product/308324709,6,o1******,2026.08.14,230,고민하다가 정사이즈로 샀는데 여유가 있습니다 디자인은 생각했던대로 귀여워요,5.0,"{'사이즈': '큼', '색상': '같음', '발볼': '적당함'}",[https://media.wconcept.co.kr/review/308324709...

In [ ]:
# 데이터 수집 -> 저장!!!
# 200개 상품 => 상품당 리뷰 1000개 200,000개 (엑셀)
# 빅데이터를 효율적으로 관리할 수 있는 곳에 저장!!!